# Generated by Django 3.1.1 on 2021-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20210319_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cameraStatus',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
